# k8s-monitoring Standalone Configuration
# 독립 실행형 설정 (Prometheus, Loki 포함)

# 클러스터 정보
cluster:
  name: "my-k8s-cluster"

# 데이터 전송 목적지 - 로컬 Prometheus와 Loki 사용
destinations:
  # 로컬 Prometheus로 메트릭 전송
  - name: "prometheus"
    type: "prometheus"
    url: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
  
  # 로컬 Loki로 로그 전송
  - name: "loki"
    type: "loki"
    url: "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"

# 전역 설정
global:
  scrapeInterval: "30s"
  maxCacheSize: 100000

# 모든 Alloy 컬렉터 활성화
alloy-logs:
  enabled: true

alloy-metrics:
  enabled: true

alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
      - name: zipkin
        port: 9411
        targetPort: 9411
        protocol: TCP
      - name: jaeger-thrift-http
        port: 14268
        targetPort: 14268
        protocol: TCP

alloy-singleton:
  enabled: true

# 모든 주요 기능 활성화
clusterMetrics:
  enabled: true

clusterEvents:
  enabled: true

podLogs:
  enabled: true

nodeLogs:
  enabled: true

applicationObservability:
  enabled: true
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
    zipkin:
      enabled: true
      port: 9411
    jaeger:
      thriftHttp:
        enabled: true
        port: 14268

annotationAutodiscovery:
  enabled: true

prometheusOperatorObjects:
  enabled: true

profiling:
  enabled: true

# 서비스 통합 예제
integrations:
  # Redis 모니터링 (필요시 활성화)
  # redis:
  #   enabled: true
  #   instances:
  #     - redis_addr: "redis.default.svc.cluster.local:6379"
  
  # MySQL 모니터링 (필요시 활성화)
  # mysql:
  #   enabled: true
  #   instances:
  #     - data_source_name: "user:password@tcp(mysql.default.svc.cluster.local:3306)/"

# 자체 보고
selfReporting:
  enabled: true
  scrapeInterval: "60s"

# Alloy Operator
alloy-operator:
  deploy: true
