# 최소 Loki 설정
deploymentMode: SingleBinary

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'

singleBinary:
  replicas: 1

# 다른 모드 비활성화
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0
gateway:
  replicas: 0

# 테스트용 스키마 사용
test:
  enabled: false

# 모니터링 비활성화
monitoring:
  dashboards:
    enabled: false
  rules:
    enabled: false
  serviceMonitor:
    enabled: false
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false

# 캐시 비활성화
chunksCache:
  enabled: false
resultsCache:
  enabled: false

# 서비스 설정
service:
  type: ClusterIP
  port: 3100
