# Loki 설정
image:
  # 최신 이미지 사용
  repository: grafana/loki

# 테스트 스키마 사용 (간단한 설정)
loki:
  useTestSchema: true
  auth_enabled: false

# 영구 저장소 설정 (파일시스템 기반)
persistence:
  enabled: true
  storageClassName: standard
  size: 10Gi

# 서비스 설정
service:
  type: ClusterIP
  port: 3100

# 리소스 제한
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

# 단일 인스턴스 배포 (스토리지 오류 방지)
replicas: 1

# 배포 방식 설정
deploymentMode: SingleBinary

# 보안 컨텍스트 설정
securityContext:
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
