# Promtail 설정
image:
  # 최신 이미지 사용
  repository: grafana/promtail

# Promtail 설정
config:
  serverPort: 3101
  clients:
    - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

# 로그 수집 설정
defaultVolumes:
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
  - name: run-promtail
    emptyDir: {}

defaultVolumeMounts:
  - name: varlog
    mountPath: /var/log
    readOnly: true
  - name: varlibdockercontainers
    mountPath: /var/lib/docker/containers
    readOnly: true
  - name: run-promtail
    mountPath: /run/promtail
    # positions 파일 저장용

# DaemonSet으로 배포 (모든 노드에서 로그 수집)
daemonset:
  enabled: true

# 서비스 설정
service:
  enabled: true
  type: ClusterIP
  port: 3101

# 리소스 제한
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

# 보안 설정
securityContext:
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsUser: 0

# 톨러레이션 설정 (마스터 노드에서도 실행)
tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
