# 간단한 Tempo 설정
image:
  repository: grafana/tempo

# 간단한 구성
tempo:
  config: |
    server:
      http_listen_port: 3200
      log_level: info
    
    distributor:
      receivers:
        jaeger:
          protocols:
            thrift_http:
              endpoint: 0.0.0.0:14268
            grpc:
              endpoint: 0.0.0.0:14250
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
        zipkin:
          endpoint: 0.0.0.0:9411
    
    ingester:
      trace_idle_period: 10s
      max_block_bytes: 1_000_000
      max_block_duration: 5m
    
    compactor:
      compaction:
        block_retention: 1h
    
    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/traces

# 영구 저장소 비활성화 (테스트용)
persistence:
  enabled: false

# 서비스 설정
service:
  type: ClusterIP
  port: 3200

# 리소스 제한
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

# 복제본 수
replicas: 1
