apiVersion: apps/v1
kind: Deployment
metadata:
  name: trace-generator
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trace-generator
  template:
    metadata:
      labels:
        app: trace-generator
    spec:
      containers:
      - name: trace-generator
        image: jaegertracing/example-hotrod:1.22
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: JAEGER_ENDPOINT
          value: "http://tempo.monitoring.svc.cluster.local:14268/api/traces"
        - name: JAEGER_AGENT_HOST
          value: "tempo.monitoring.svc.cluster.local"
        - name: JAEGER_AGENT_PORT
          value: "6831"
        - name: JAEGER_SAMPLER_TYPE
          value: "const"
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: trace-generator
  namespace: monitoring
spec:
  selector:
    app: trace-generator
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trace-generator-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: hotrod.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: trace-generator
            port:
              number: 8080
