# Loki Stack Values
# Minimal configuration for WSL2 + minikube

# Single binary mode for simplicity
deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  
  # Resources
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

# Basic Loki configuration
loki:
  auth_enabled: false

# Storage
persistence:
  enabled: true
  size: 10Gi

# Service
service:
  type: ClusterIP
  port: 3100

# Disable monitoring
monitoring:
  serviceMonitor:
    enabled: false

# Disable test pods
test:
  enabled: false
