# k8s-monitoring Helm Chart Values
# 기본 Kubernetes 모니터링 설정

# 클러스터 정보
cluster:
  name: "my-k8s-cluster"  # 클러스터 이름을 실제 환경에 맞게 변경하세요

# 데이터 전송 목적지 설정
destinations:
  # 기본적으로 빈 배열로 설정 (외부 목적지 사용)
  # 실제 사용 시 아래 예제를 참고하여 설정하세요
  []
  
  # Prometheus Remote Write 예제:
  # - name: "prometheus"
  #   type: "prometheus"
  #   url: "http://prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
  
  # Loki 예제:
  # - name: "loki"
  #   type: "loki"
  #   url: "http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push"
  
  # OTLP 예제:
  # - name: "otlp"
  #   type: "otlp"
  #   url: "http://jaeger-collector.monitoring.svc.cluster.local:4317"

# 전역 설정
global:
  scrapeInterval: "30s"
  maxCacheSize: 100000
  platform: ""  # "openshift" for OpenShift clusters

# Alloy 컬렉터 설정
alloy-logs:
  enabled: true
  # 로그 수집을 위한 DaemonSet

alloy-metrics:
  enabled: true
  # 메트릭 수집을 위한 StatefulSet

alloy-receiver:
  enabled: true
  # 애플리케이션 데이터 수신을 위한 Deployment
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP
      - name: zipkin
        port: 9411
        targetPort: 9411
        protocol: TCP
      - name: jaeger-thrift-http
        port: 14268
        targetPort: 14268
        protocol: TCP

alloy-singleton:
  enabled: true
  # 단일 인스턴스가 필요한 작업들

# 기능 활성화 설정
clusterMetrics:
  enabled: true
  # Kubernetes 클러스터 메트릭 수집 (CPU, 메모리, 네트워크 등)

clusterEvents:
  enabled: true
  # Kubernetes 이벤트 로그 수집

podLogs:
  enabled: true
  # Pod 로그 수집

nodeLogs:
  enabled: false
  # 노드 시스템 로그 수집 (필요시 활성화)

applicationObservability:
  enabled: true
  # 애플리케이션 관찰성 (메트릭, 로그, 트레이스)
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318
    zipkin:
      enabled: true
      port: 9411
    jaeger:
      thriftHttp:
        enabled: true
        port: 14268

annotationAutodiscovery:
  enabled: true
  # 어노테이션 기반 자동 메트릭 수집

prometheusOperatorObjects:
  enabled: true
  # Prometheus Operator 객체 지원 (ServiceMonitor, PodMonitor 등)

profiling:
  enabled: false
  # 프로파일링 (필요시 활성화)

autoInstrumentation:
  enabled: false
  # 자동 계측 (Beyla 사용, 필요시 활성화)

# 서비스 통합
integrations:
  # 일반적인 서비스들의 메트릭 수집
  # 필요한 서비스만 활성화하세요
  
# 자체 보고 설정
selfReporting:
  enabled: true
  scrapeInterval: "60s"

# Alloy Operator 설정
alloy-operator:
  deploy: true

# 추가 매니페스트 객체
extraObjects: []

# 리소스 제한 (필요시 조정)
# alloy-logs:
#   alloy:
#     resources:
#       requests:
#         memory: "128Mi"
#         cpu: "100m"
#       limits:
#         memory: "512Mi"
#         cpu: "500m"

# alloy-metrics:
#   alloy:
#     resources:
#       requests:
#         memory: "256Mi"
#         cpu: "200m"
#       limits:
#         memory: "1Gi"
#         cpu: "1000m"
