# Prometheus Values for kube-prometheus-stack
# 독립 실행형 Prometheus 설정

# 전역 설정
fullnameOverride: "prometheus"

# Grafana 비활성화 (별도 설치)
grafana:
  enabled: false

# 이 섹션은 아래로 이동됨
  
  # AlertManager 서비스 설정
  service:
    type: ClusterIP
    port: 9093
    nodePort: ""
  
  # AlertManager Ingress 설정 (필요시 활성화)
  ingress:
    enabled: false
    # annotations: {}
    # hosts:
    #   - alertmanager.local
    # tls: []

# Prometheus Server 설정
prometheus:
  enabled: true
  prometheusSpec:
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    
    # 리소스 설정
    resources:
      requests:
        memory: 2Gi
        cpu: 1000m
      limits:
        memory: 4Gi
        cpu: 2000m
    
    # 외부 접근 설정
    externalUrl: ""
    
    # Remote Write 설정 (필요시)
    remoteWrite: []
    
    # Remote Read 설정 (필요시)
    remoteRead: []
    
    # 추가 scrape configs
    additionalScrapeConfigs: []
  
  # 서비스 설정
  service:
    type: ClusterIP
    port: 9090
    nodePort: ""
  
  # Ingress 설정 (필요시 활성화)
  ingress:
    enabled: false
    # annotations: {}
    # hosts:
    #   - prometheus.local
    # tls: []

# Node Exporter 설정
nodeExporter:
  enabled: true

# kube-state-metrics 설정
kubeStateMetrics:
  enabled: true

# Prometheus Operator 설정
prometheusOperator:
  enabled: true
  
  # 리소스 설정
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m
