apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt ACME 서버 URL (프로덕션)
    server: https://acme-v02.api.letsencrypt.org/directory
    
    # 인증서 발급을 위한 이메일 주소 (실제 이메일로 변경하세요)
    email: bahn1075@naver.com
    
    # ACME 계정의 개인 키를 저장할 Secret 이름
    privateKeySecretRef:
      name: letsencrypt-prod
    
    # HTTP-01 챌린지 솔버 설정 (nginx-ingress와 연동)
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
      selector: {}

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt ACME 서버 URL (스테이징/테스트)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    
    # 인증서 발급을 위한 이메일 주소 (실제 이메일로 변경하세요)
    email: bahn1075@naver.com
    
    # ACME 계정의 개인 키를 저장할 Secret 이름
    privateKeySecretRef:
      name: letsencrypt-staging
    
    # HTTP-01 챌린지 솔버 설정 (nginx-ingress와 연동)
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
      selector: {}
