# k8s-monitoring with Grafana Cloud Configuration
# Grafana Cloud로 데이터를 전송하는 설정

# 클러스터 정보
cluster:
  name: "my-k8s-cluster"

# Grafana Cloud 목적지 설정
# 실제 사용 시 아래 값들을 Grafana Cloud에서 제공하는 값으로 변경하세요
destinations:
  # Grafana Cloud Prometheus
  - name: "grafana-cloud-prometheus"
    type: "prometheus"
    url: "https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push"
    auth:
      type: "basic"
      username: "YOUR_PROMETHEUS_USERNAME"  # 실제 값으로 변경
      password: "YOUR_PROMETHEUS_API_KEY"   # 실제 값으로 변경
  
  # Grafana Cloud Loki
  - name: "grafana-cloud-loki"
    type: "loki"
    url: "https://logs-prod-us-central1.grafana.net/loki/api/v1/push"
    auth:
      type: "basic"
      username: "YOUR_LOKI_USERNAME"        # 실제 값으로 변경
      password: "YOUR_LOKI_API_KEY"         # 실제 값으로 변경
  
  # Grafana Cloud Tempo (트레이싱)
  - name: "grafana-cloud-tempo"
    type: "otlp"
    url: "https://tempo-prod-04-prod-us-central-0.grafana.net:443"
    auth:
      type: "basic"
      username: "YOUR_TEMPO_USERNAME"       # 실제 값으로 변경
      password: "YOUR_TEMPO_API_KEY"        # 실제 값으로 변경
  
  # Grafana Cloud Pyroscope (프로파일링)
  - name: "grafana-cloud-pyroscope"
    type: "pyroscope"
    url: "https://profiles-prod-001.grafana.net"
    auth:
      type: "basic"
      username: "YOUR_PYROSCOPE_USERNAME"   # 실제 값으로 변경
      password: "YOUR_PYROSCOPE_API_KEY"    # 실제 값으로 변경

# 전역 설정
global:
  scrapeInterval: "60s"  # Cloud로 전송하므로 간격을 늘림
  maxCacheSize: 100000

# Alloy 컬렉터 설정
alloy-logs:
  enabled: true

alloy-metrics:
  enabled: true

alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        targetPort: 4318
        protocol: TCP

alloy-singleton:
  enabled: true

# 주요 기능 활성화
clusterMetrics:
  enabled: true
  # Grafana Cloud로만 전송
  destinations: ["grafana-cloud-prometheus"]

clusterEvents:
  enabled: true
  # Grafana Cloud Loki로만 전송
  destinations: ["grafana-cloud-loki"]

podLogs:
  enabled: true
  # Grafana Cloud Loki로만 전송
  destinations: ["grafana-cloud-loki"]

nodeLogs:
  enabled: false  # 민감한 정보가 포함될 수 있으므로 비활성화

applicationObservability:
  enabled: true
  # 모든 관련 목적지로 전송
  destinations: 
    - "grafana-cloud-prometheus"
    - "grafana-cloud-loki"
    - "grafana-cloud-tempo"
  receivers:
    otlp:
      grpc:
        enabled: true
        port: 4317
      http:
        enabled: true
        port: 4318

annotationAutodiscovery:
  enabled: true
  destinations: ["grafana-cloud-prometheus"]

prometheusOperatorObjects:
  enabled: true
  destinations: ["grafana-cloud-prometheus"]

profiling:
  enabled: true
  destinations: ["grafana-cloud-pyroscope"]

# 자체 보고 (Alloy 자체 메트릭)
selfReporting:
  enabled: true
  scrapeInterval: "60s"
  destinations: ["grafana-cloud-prometheus"]

# Alloy Operator
alloy-operator:
  deploy: true
